include:
   - project: nse/ci
     file:
        - /ci/lib/tox-bb5.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/py36.yml
        - /ci/jobs/py37.yml
        - /ci/jobs/py38.yml
        - /ci/jobs/docs.yml
        - /ci/jobs/build-package.yml
        - /ci/jobs/publish-package.yml
        - /ci/jobs/publish-docs.yml
        - /ci/jobs/tag.yml
   - project: neuromath/ci
     file:
        - /ci/jobs/auto-release.yml

.tox-template:
  variables:
    EXTRA_MODULES: archive/2021-05:py-mpi4py
    bb5_cpus_per_task: 5

docs:
  variables:
    EXTRA_MODULES: archive/2021-05:py-mpi4py

py37-MPI:
  extends: .tox-template
  variables:
    TOXENV: py37-MPI
    bb5_ntasks: 5
    bb5_constraint: cpu
